name: Build and Attach Artifact from Another Repository

on:
  push:
    branches:
      - main

jobs:
  checkout-build-attach:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository code
      #- name: Checkout Current Repository
      #  uses: actions/checkout@v3

      # Step 2: Checkout another repository (Target Repository)
      - name: Checkout Another Repository
        uses: actions/checkout@v3
        with:
          repository: mpointner/user-administration
          ref: main # Replace with the target branch name
          token: ${{ secrets.PAT_USER_ADMINISTRATION }}
          #path: target-repo # Check out the code in a directory called 'target-repo'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 4: Build the Project with Gradle
      - name: Build with Gradle
        #working-directory: target-repo # Point to 'target-repo' directory
        run: ./gradlew build -x test

      # Step 5: Attach the Artifact
      - name: Attach Build Artifact
        #working-directory: target-repo # Point to 'target-repo' directory
        run: |
          mkdir -p ../artifacts

      - name: Upload Artifacts to the Workflow Run
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
          retention-days: 5
